# Generated by Django 4.0.1 on 2025-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0002_slidercaptcha_adminuser_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfig',
            name='api_type',
        ),
        migrations.RemoveField(
            model_name='queryconfig',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='queryconfig',
            name='result_types',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='api_code',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='接口编号'),
        ),
    ]
