# Generated by Django 4.0.1 on 2025-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0006_remove_agentuser_permission1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='username',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='用户ID'),
        ),
    ]
