# Generated by Django 4.0.1 on 2025-07-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0007_regularuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalapiconfig',
            options={'verbose_name': '外部API接口配置', 'verbose_name_plural': '外部API接口配置'},
        ),
        migrations.AddField(
            model_name='externalapiconfig',
            name='credentials',
            field=models.JSONField(default=None, verbose_name='加密凭证 (JSON格式)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='customer_service_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='客服链接'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='force_wechat_access',
            field=models.BooleanField(default=False, verbose_name='仅支持微信生态打开'),
        ),
        migrations.AlterField(
            model_name='externalapiconfig',
            name='config_name',
            field=models.CharField(max_length=100, verbose_name='配置名称 (方便后台识别)'),
        ),
        migrations.AlterField(
            model_name='externalapiconfig',
            name='config_type',
            field=models.CharField(choices=[('tianyuan_risk_api', '天远风险查询'), ('aliyun_sms', '阿里云短信'), ('wechat_oauth', '微信公众号登录')], max_length=50, verbose_name='配置类型'),
        ),
        migrations.AlterField(
            model_name='externalapiconfig',
            name='owner_id',
            field=models.IntegerField(default=1, verbose_name='所属用户ID'),
        ),
        migrations.AlterField(
            model_name='externalapiconfig',
            name='owner_type',
            field=models.CharField(choices=[('admin', '管理员'), ('agent', '代理')], default='admin', max_length=10, verbose_name='用户类型'),
        ),
        migrations.AlterUniqueTogether(
            name='externalapiconfig',
            unique_together={('config_type', 'owner_id', 'owner_type')},
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='access_key_id',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='access_key_secret',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='app_secret',
        ),
        migrations.RemoveField(
            model_name='externalapiconfig',
            name='redirect_domain',
        ),
    ]
