# Generated by Django 4.0.1 on 2025-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0008_alter_externalapiconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerificationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
                'db_table': 'sms_verification_codes',
            },
        ),
        migrations.DeleteModel(
            name='PaymentConfig',
        ),
        migrations.AddField(
            model_name='regularuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='注销时间'),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_deactivated',
            field=models.BooleanField(default=False, verbose_name='是否已注销'),
        ),
        migrations.AlterField(
            model_name='externalapiconfig',
            name='config_type',
            field=models.CharField(choices=[('tianyuan_risk_api', '天远风险查询'), ('aliyun_sms', '阿里云短信'), ('wechat_oauth', '微信公众号登录'), ('alipay_payment', '支付宝支付'), ('wechat_payment', '微信支付')], max_length=50, verbose_name='配置类型'),
        ),
    ]
