# Generated by Django 4.0.1 on 2025-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0009_smsverificationcode_delete_paymentconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='enterprise_query_customer_price',
        ),
        migrations.RemoveField(
            model_name='agentuser',
            name='enterprise_query_min_price',
        ),
        migrations.RemoveField(
            model_name='agentuser',
            name='personal_query_customer_price',
        ),
        migrations.RemoveField(
            model_name='agentuser',
            name='personal_query_min_price',
        ),
        migrations.AddField(
            model_name='agentuser',
            name='can_customize_apis',
            field=models.BooleanField(default=False, verbose_name='允许自定义接口搭配'),
        ),
        migrations.AddField(
            model_name='agentuser',
            name='follow_main_config',
            field=models.BooleanField(default=True, verbose_name='跟随主站配置'),
        ),
    ]
