# Generated by Django 4.0.1 on 2025-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0010_remove_agentuser_enterprise_query_customer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='can_customize_apis',
        ),
        migrations.RemoveField(
            model_name='agentuser',
            name='follow_main_config',
        ),
        migrations.AddField(
            model_name='agentuser',
            name='enterprise_query_min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='企业查询最低价格'),
        ),
        migrations.AddField(
            model_name='agentuser',
            name='personal_query_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人查询价格'),
        ),
    ]
