# Generated by Django 4.0.1 on 2025-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0011_remove_agentuser_can_customize_apis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(verbose_name='关联订单ID')),
                ('encrypted_result_data', models.TextField(blank=True, null=True, verbose_name='加密的查询结果')),
                ('result_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='结果完整性校验')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='processing', max_length=20, verbose_name='查询状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间(7天后自动删除)')),
            ],
            options={
                'verbose_name': '查询结果',
                'verbose_name_plural': '查询结果',
                'db_table': 'query_results',
            },
        ),
        migrations.AddField(
            model_name='agentuser',
            name='settled_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='累计结算佣金'),
        ),
        migrations.AddField(
            model_name='agentuser',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='累计佣金'),
        ),
        migrations.AddField(
            model_name='agentuser',
            name='unsettled_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='未结算佣金'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='代理佣金'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式: alipay/wechat'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='query_complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='查询完成时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='query_config_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='查询配置ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='query_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='查询开始时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='third_party_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='third_party_trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方交易号'),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='personal_query_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人查询最低价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('querying', '查询中'), ('completed', '查询完成'), ('failed', '查询失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='orders_order_n_a26108_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', 'created_at'], name='orders_user_id_51663a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agent_id', 'created_at'], name='orders_agent_i_9a0626_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['order_id'], name='query_resul_order_i_700172_idx'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['expires_at'], name='query_resul_expires_5e8de8_idx'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['status', 'created_at'], name='query_resul_status_b31f58_idx'),
        ),
    ]
