# Generated by Django 4.0.1 on 2025-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0013_apiconfig_requires_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'verbose_name': 'API配置', 'verbose_name_plural': 'API配置'},
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='param_config',
            field=models.JSONField(default=dict, help_text='JSON格式的参数配置', verbose_name='参数配置'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='admin_cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='管理员成本价格'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='api_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='API编号'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='api_name',
            field=models.CharField(max_length=100, verbose_name='API名称'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='成本价格'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='owner_id',
            field=models.IntegerField(verbose_name='所属用户ID'),
        ),
        migrations.AddIndex(
            model_name='apiconfig',
            index=models.Index(fields=['owner_id', 'owner_type'], name='api_configs_owner_i_d13ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiconfig',
            index=models.Index(fields=['api_code'], name='api_configs_api_cod_8ec8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiconfig',
            index=models.Index(fields=['is_active'], name='api_configs_is_acti_ccd142_idx'),
        ),
    ]
