# Generated by Django 4.0.1 on 2025-07-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0014_alter_apiconfig_options_apiconfig_param_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryHistory',
        ),
        migrations.AddField(
            model_name='queryresult',
            name='agent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='代理ID'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='查询费用'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='user_id',
            field=models.IntegerField(default=None, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='order_id',
            field=models.BigIntegerField(default=None, verbose_name='关联订单ID'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['user_id', 'created_at'], name='query_resul_user_id_c75203_idx'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['agent_id', 'created_at'], name='query_resul_agent_i_4eaf9e_idx'),
        ),
    ]
