# Generated by Django 4.0.1 on 2025-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0015_delete_queryhistory_queryresult_agent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='关联订单ID'),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户ID'),
        ),
    ]
