# Generated by Django 4.0.1 on 2025-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0016_alter_queryresult_order_id_alter_queryresult_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='是否已过期'),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='expires_at',
            field=models.DateTimeField(verbose_name='过期时间(30天后自动过期)'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['is_expired'], name='query_resul_is_expi_f63bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['is_expired', 'expires_at'], name='query_resul_is_expi_947e87_idx'),
        ),
    ]
