# Generated by Django 4.0.1 on 2025-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0017_queryresult_is_expired_alter_queryresult_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='微信OpenID'),
        ),
    ]
