# Generated by Django 4.0.1 on 2025-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0018_alter_regularuser_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
    ]
