# Generated by Django 4.0.1 on 2025-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0019_alter_regularuser_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationletter',
            name='authorization_file_url',
        ),
        migrations.AddField(
            model_name='authorizationletter',
            name='download_token',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='下载令牌'),
        ),
        migrations.AddField(
            model_name='authorizationletter',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='授权书文件路径'),
        ),
        migrations.AddField(
            model_name='authorizationletter',
            name='masked_id_card',
            field=models.CharField(default='', max_length=20, verbose_name='脱敏身份证号'),
        ),
        migrations.AddField(
            model_name='authorizationletter',
            name='masked_name',
            field=models.CharField(default='', max_length=50, verbose_name='脱敏姓名'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='公司名称'),
        ),
        migrations.AddIndex(
            model_name='authorizationletter',
            index=models.Index(fields=['download_token'], name='authorizati_downloa_b1efbf_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationletter',
            index=models.Index(fields=['user_id', 'created_at'], name='authorizati_user_id_333578_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationletter',
            index=models.Index(fields=['agent_id', 'created_at'], name='authorizati_agent_i_6358bd_idx'),
        ),
    ]
