# Generated by Django 4.0.1 on 2025-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0020_remove_authorizationletter_authorization_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('querying', '查询中'), ('completed', '查询完成'), ('failed', '查询失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
