# Generated by Django 4.0.1 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0021_order_refund_time_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申请用户姓名')),
                ('contact_type', models.CharField(choices=[('wechat', '微信'), ('phone', '手机号')], max_length=10, verbose_name='联系方式类别')),
                ('contact_info', models.CharField(max_length=100, verbose_name='联系方式')),
                ('application_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '代理申请',
                'verbose_name_plural': '代理申请',
                'db_table': 'agent_applications',
            },
        ),
        migrations.AddIndex(
            model_name='agentapplication',
            index=models.Index(fields=['application_time'], name='agent_appli_applica_28d889_idx'),
        ),
        migrations.AddIndex(
            model_name='agentapplication',
            index=models.Index(fields=['contact_type'], name='agent_appli_contact_3dd16a_idx'),
        ),
    ]
