# Generated by Django 4.0.1 on 2025-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0022_agentapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联用户ID'),
        ),
        migrations.AddIndex(
            model_name='agentapplication',
            index=models.Index(fields=['user_id'], name='agent_appli_user_id_1447e4_idx'),
        ),
    ]
