# Generated by Django 4.0.1 on 2025-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0023_agentapplication_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPaymentConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField(unique=True, verbose_name='代理ID')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], max_length=10, verbose_name='收款方式')),
                ('payment_account', models.CharField(max_length=100, verbose_name='收款账号')),
                ('payment_name', models.CharField(max_length=50, verbose_name='收款人姓名')),
                ('payment_qr_code', models.CharField(blank=True, max_length=500, verbose_name='收款码图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理收款配置',
                'verbose_name_plural': '代理收款配置',
                'db_table': 'agent_payment_configs',
            },
        ),
        migrations.CreateModel(
            name='CommissionWithdrawal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField(verbose_name='代理ID')),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='提现金额')),
                ('unsettled_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请时未结算金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '佣金提现申请',
                'verbose_name_plural': '佣金提现申请',
                'db_table': 'commission_withdrawals',
            },
        ),
        migrations.AddIndex(
            model_name='commissionwithdrawal',
            index=models.Index(fields=['agent_id', 'created_at'], name='commission__agent_i_b07e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionwithdrawal',
            index=models.Index(fields=['status', 'created_at'], name='commission__status_9c2eea_idx'),
        ),
        migrations.AddIndex(
            model_name='agentpaymentconfig',
            index=models.Index(fields=['agent_id'], name='agent_payme_agent_i_1bfa7f_idx'),
        ),
    ]
