# Generated by Django 5.2.4 on 2025-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApi", "0024_agentpaymentconfig_commissionwithdrawal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularuser",
            name="alipay_user_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="支付宝用户ID",
            ),
        ),
    ]
